### ISSUE TITLE
how to change the background colour?

### ISSUE THREAD

**Issue by McDreamy** [magicwing/react-native-image-zoom-viewer#7]
I would like to change to dark background to white background.
Anyway to do this?

**Comment by McDreamy** [comment]
is okay, I found away.

**Comment by Dias999** [comment]
In case anyone gets here wondering the answer:
Just add `backgroundColor={String}` prop to ImageViewer component.

```
<ImageViewer imageUrls={...} backgroundColor={'#660099'} />
```
